This IGERT-inspired code was written by Rob Fatland (2015) with two purposes

1. Introduction to python by example with extensive remarks. "Any line of code (that does not have an accompanying comment is an error.")

2. Create a through-line from mathematics to a problem in estuary circulation.

This motivates boating excursions to estuaries. ("Believe me, my young friend, there is nothing—-absolutely nothing—-half so much worth doing as simply messing about in boats.")

From Oceanography:
Blue crab larvae and other zooplankton spend lots of time in estuaries
Buckets of water from estuaries can be subjected to analysis, collectively H2Omes.
Sequencing to genes to metagenomes.
Spectral analysis of dissolved organics: mass spectrometry, color, fluorescence, etc. 
Sample metadata (assay methods): total carbon, pH, etcetera
Cytomes: From a flow cytometer

From Mathematics:
A graph G is a pair of sets V and E where E are pairs of elements of V. 
Graphs in turn have properties: Girth, circumference, presence/absence of Hamiltonian cycles, etc.
Graphs can be represented in terms of various connectivity matrices.
These include the 'Laplacian' forms.
Graph matrices, in turn, have characteristic polynomials and eigenvalues that may be related to properties of the graph.
Specifically we could describe the conditional probability distribution of plankton in an estuary using Markov process theory which in turn can be associated with attributes of graphs. 

The resulting research might proceed from observations of the estuary { plankton, light, water chemistry, etc} to produce a predictive model. The model would be tested; hence the research provides two opportunities to go float around an estuary in a boat. 


In [2]:
# for linear algebra I import numpy and related topics with abbreviations: 
#   'la' for linear algebra methods, etcetera
import numpy
import numpy.linalg as la

# for charting (matplotlib) I import scipy and a subset as 'chart'
import scipy as s
pi = s.pi()
print pi

# pandas: for analysis and more practically for reading CSV files into a data structure
import pandas

# os: for file listings and changing directories
import os


TypeError: 'float' object is not callable

In [3]:
# This will eventually be the Laplacian matrix representation of a graph
Laplacian = numpy.matrix([[1,1,0],[1,0,1],[0,1,1]])
print 'L = ', Laplacian
print ''
print 'inverse L = ', la.inv(Laplacian)
print 'eigenvalues of L = ', la.eigvals(Laplacian)
print 'determinant L = ', la.det(Laplacian)


#############
##
## This section is motivated by Make Your Own CTD
##
#############

####
# 
# Decimal readout of a parallel (MSB to LSB) signal
#
####

# We have an analog-to-digital converter from Texas Instruments that produces a parallel
#   signal 1000 times per second. The signal is 8 bits of readout, each 'hi' or 'lo', that
#   translates from binary to a decimal number between 0 and 255 inclusive. Let's create a 
#   digital readout of that number on a three digit display, in fact 3 7-segment LEDs. 
# Run through a loop and determine what digits to place in a 3 x 7-segment LED display
for i7 in range(2):
    for i6 in range(2):
        for i5 in range(2):
            for i4 in range(2):
                for i3 in range(2):
                    for i2 in range(2):
                        for i1 in range(2):
                            for i0 in range(2):
                                adc = i7*128 + i6*64 + i5*32 + i4*16 + i3*8 + i2*4 + i1*2 + i0
                                if (s.mod(adc,10) == 0):
                                    print 'adc = ', adc
                                    

                                    
###############
##
## CSV file of FT-ICR mass spectrometer peak list 
##
###############
# os.chdir('C:\\Users\\robfat\\Documents\\Data\\BDS Create Test Backup\\Beaches_2014')
# os.getcwd()
# data=pandas.read_table('.\csvexample.csv')
# print data

#####################
##
## Flow Cytometer data reduction
##
#####################

# os.chdir('G:\pc\Data\UW Oceanography\Sophie')
# os.getcwd()
# data=pandas.read_table('.\ct_one_day.csv')
# print data


L =  [[1 1 0]
 [1 0 1]
 [0 1 1]]

inverse L =  [[ 0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]]
eigenvalues of L =  [-1.  1.  2.]
determinant L =  -2.0
adc =  0
adc =  10
adc =  20
adc =  30
adc =  40
adc =  50
adc =  60
adc =  70
adc =  80
adc =  90
adc =  100
adc =  110
adc =  120
adc =  130
adc =  140
adc =  150
adc =  160
adc =  170
adc =  180
adc =  190
adc =  200
adc =  210
adc =  220
adc =  230
adc =  240
adc =  250
